services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app
        - action: rebuild
          path: ./frontend/package.json
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app_network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - "__pycache__/"
        - action: rebuild
          path: ./backend/requirements.txt
    volumes:
      - ./backend:/app
    networks:
      - app_network
    environment:
      - DATABASE_URI=mysql://user:password@db/rarecheck
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rarecheck
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app_network

networks:
  app_network:
