services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: rarecheck_frontend_container
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app
        - action: rebuild
          path: ./frontend/package.json
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app_network
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: rarecheck_backend_container
    ports:
      - "5000:5000"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - "__pycache__/"
        - action: rebuild
          path: ./backend/requirements.txt
    volumes:
      - ./backend:/app
    networks:
      - app_network
    environment:
      - DATABASE_URI=${DATABASE_URI}
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: rarecheck_db_container
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - app_network

networks:
  app_network:
