export const createdQuestionRows = [
  {
    id: 1,
    question: "コンピュータのCPUの役割は何ですか？",
    category: "コンピュータ",
    step: "",
    date: new Date("2024-10-31"),
    hasComment: false,
    isAccepted: true,
  },
  {
    id: 2,
    question: "インターネットで使われるIPアドレスとは何ですか？",
    category: "ネットワーク",
    step: 5,
    date: new Date("2024-11-01"),
    hasComment: true,
    isAccepted: false,
  },
  {
    id: 3,
    question: "HTMLとは何の略ですか？",
    category: "ウェブデザイン",
    step: 3,
    date: new Date("2024-11-02"),
    hasComment: false,
    isAccepted: true,
  },
  {
    id: 4,
    question: "プログラミング言語Pythonの特徴は何ですか？",
    category: "プログラミング",
    step: 8,
    date: new Date("2024-10-25"),
    hasComment: true,
    isAccepted: false,
  },
  {
    id: 5,
    question: "HTTPとHTTPSの違いは何ですか？",
    category: "セキュリティ",
    step: "",
    date: new Date("2024-10-20"),
    hasComment: false,
    isAccepted: true,
  },
  {
    id: 6,
    question: "ウェブサイトにアクセスするためのドメイン名とは何ですか？",
    category: "インターネット",
    step: 7,
    date: new Date("2024-11-05"),
    hasComment: true,
    isAccepted: true,
  },
  {
    id: 7,
    question: "プログラミング言語Javaの特徴は何ですか？",
    category: "プログラミング",
    step: 10,
    date: new Date("2024-10-15"),
    hasComment: false,
    isAccepted: false,
  },
  {
    id: 8,
    question: "AIと機械学習の違いは何ですか？",
    category: "AI",
    step: 4,
    date: new Date("2024-11-10"),
    hasComment: true,
    isAccepted: true,
  },
  {
    id: 9,
    question: "Gitとは何ですか？",
    category: "ツール",
    step: "",
    date: new Date("2024-11-07"),
    hasComment: false,
    isAccepted: true,
  },
  {
    id: 10,
    question: "データベースの正規化とは何ですか？",
    category: "データベース",
    step: 9,
    date: new Date("2024-10-30"),
    hasComment: true,
    isAccepted: false,
  },
];
